using Homework;
using static System.Console;
Thread myThread1 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(1)));
Thread myThread2 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(2)));
Thread myThread3 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(3)));
Thread myThread4 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(4)));
Thread myThread5 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(5)));
Thread myThread6 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(6)));
Thread myThread7 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(7)));
Thread myThread8 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(8)));
Thread myThread9 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(9)));
Thread myThread10 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(10)));
Thread myThread11 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(11)));
Thread myThread12 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(12)));
Thread myThread13 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(13)));
Thread myThread14 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(14)));
Thread myThread15 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(15)));
Thread myThread16 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(16)));
Thread myThread17 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(17)));
Thread myThread18 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(18)));
Thread myThread19 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(19)));
Thread myThread20 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(20)));
//Thread myThread21 = new(new ThreadStart(() => WorkingWithThreads.MyThreadMethod(21)));
myThread1.Start();
myThread2.Start();
myThread3.Start();
myThread4.Start();
myThread5.Start();
myThread6.Start();
myThread7.Start();
myThread8.Start();
myThread9.Start();
myThread10.Start();
myThread11.Start();
myThread12.Start();
myThread13.Start();
myThread14.Start();
myThread15.Start();
myThread16.Start();
myThread17.Start();
myThread18.Start();
myThread19.Start();
myThread20.Start();
//myThread21.Start();